spring:
  application:
    name: "configserver"
  profiles:
#    git is put when we want to pull the config files from github repo so that it is not visible to everyone
    active: git
#    native is put if we are adding config files from same project or from local system
#    active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Sushmit1480/eazybytes-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
#        native:
#          search-locations: "classpath:/config"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enable: true
    liveness-state:
      enable: true
  endpoint:
    health:
      probes:
        enable: true

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

server:
  port:
    8071